AJ/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView

app_name = 'AJ'
urlpatterns = [
    path('',TemplateView.as_view(template_name="AJ/home.html"),name="homeAj"),
    path('about/',views.about,name='about'),
    path('resume/',views.resume,name='resume'),
    path('services/',views.services,name='services'),
    path('portfolio/',views.portfolio,name='portfolio'),
    path('logIn/',views.LogIn,name='LogIn'),

]

Contacto/urls.py
from django.urls import path

from Contacto import views

app_name = 'Contacto'
urlpatterns = [
    # path('contact',views.contact,name='contact'), #Cuando llama a la vista normal
    path('contact/',views.contactForm,name='contact') #Cuando llama al template con forms, el name es el URL que se ve

]

PagAJ/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import TemplateView






urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('AJ.urls')),
    path('contacto/',include('Contacto.urls')),
]

AJ/models.py
from django.db import models

# Create your models here.

class Cliente(models.Model):
    nombre=models.CharField(max_length=50)
    apellido=models.CharField(max_length=50)
    email=models.EmailField()






    

Contacto/models.py
from django.db import models
from django.core.validators import validate_email,validate_slug

# Create your models here.
class Cliente_Contacto (models.Model):
    name=models.CharField(validators=[validate_slug],max_length=50,verbose_name="Name")
    email=models.EmailField(validators=[validate_email],verbose_name="Email")
    
    class Meta:
        #db_table = 'Cliente'
        verbose_name = 'Cliente'

    def __str__(self):
        return "El Clientes es %s y su email es: %s"%(self.name,self.email)
    
 
    

class Cliente_message(models.Model):
    cliente=models.ForeignKey('Cliente_Contacto',on_delete=models.PROTECT)
    message=models.TextField(verbose_name="Message")
    subject=models.CharField(max_length=100,verbose_name="Subject")
    date=models.DateTimeField(null=True,blank=True,auto_now=True)

    class Meta:
        #db_table = 'Mensaje'
        verbose_name = 'Mensaje'


    def __str__(self):
        return self.message
    
    

Contacto/forms.py
from django import forms


class ContactoForm(forms.Form):
    error_css_class = 'error'
    name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control','placeholder' : 'Your Name'}))
    subject = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control','placeholder' : 'Subject'}))
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class' : 'form-control','placeholder' : 'Your Email'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control','row' : '5','placeholder' : ' Message'}))
    
    def clean(self):
        cleaned_data = super(ContactoForm, self).clean()
        name=cleaned_data.get('name')
        subject = cleaned_data.get('subject')
        email = cleaned_data.get('email')
        message = cleaned_data.get('message')

        if not name and not subject and not email and not message:
            raise forms.ValidationError('You have to write something!')

        
        

AJ/views.py
from django.shortcuts import render

# Importaciones para el envio de mail en contacto
from django.core.mail import send_mail
from django.conf import settings
from . import views

# fin importaciones de email

# Create your views here.


def home (request):

    return render(request,'AJ/home.html')

def about (request):

    return render(request,'AJ/about.html')

def resume (request):

    return render(request,'AJ/resume.html')

def services (request):

    return render(request,'AJ/services.html')

def portfolio (request):

    return render(request,'AJ/portfolio.html')




def LogIn (reguest):
    
    return render(reguest,'AJ/LogIn.html')

Contacto/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import get_template
from django.template import Context

from django.template.loader import render_to_string 
from django.core.mail import EmailMessage

from Contacto.models import *
from Contacto.forms import  ContactoForm

import traceback

# Create your views here.
def contact (request):
    # now=datetime.now()
    if request.method=="POST":
        subject=request.POST["subject"]
        email_client=request.POST["email"]
        message=request.POST['message']+ " " + email_client
        name=request.POST["name"]
        email_from=settings.EMAIL_HOST_USER # Desde donde se envian los mensajes
        recipient_list=settings.EMAIL_HOST_RECIPIENT #A donde llegan los mensajes enviados

        #envio del email
        send_mail(subject,message,email_from,recipient_list)

        #guardar en BD.
        # Este hace un QuerySet, pero no crea el objeto
        Cliente=Cliente_Contacto.objects.filter(email=email_client)
        

        if Cliente:
            # existe


            # Cuando el email ya existe no valida el nombre
            # Modificar esta validacion

            Cliente=Cliente_Contacto.objects.get(email=email_client)
            m=Cliente_message(message=message,subject=subject,cliente=Cliente)
            m.save()        
        else:
            #No existe
            c=Cliente_Contacto(name=name,email=email_client)
            c.save()
            m=Cliente_message(message=message,subject=subject,cliente=c)
            m.save()
        return render(request,'Contacto/contact.html')

    

def envio_email(contx):

    """ Envio de template como string
        plaintext=get_template('Contacto/email.txt')
        text_content = plaintext.render(contx)
        send_mail(subject,text_content,email_from,recipient_list)"""


    htmly     = 'Contacto/email.html'
    html_message = render_to_string(htmly, contx)
    try:
        send_mail(
            contx['subject'],
            "",
            contx['email_from'],
            contx['recipient_list'],
            fail_silently=False,
            html_message=html_message,
            )
        # raise ValueError
        return 'Mensaje Enviado'
    except:
        tb = traceback.format_exc()
        return Exception('XYZ has gone wrong...')
    """ finally:
        print(tb)
        return tb  """
        
    

    """ Esta funcion EmailMessage es otra opcion para enviar mensajes
        message_html = EmailMessage(subject, html_message, email_from, recipient_list)
        message_html.content_subtype = 'html' # this is required because there is no plain text email version
        message_html.send() """



def contactForm (request):
    ''' Utilizando la API FORMS de Django'''
    if request.method=="POST":
        #Guarda la informacion del formulario en variables.
        email_from=settings.EMAIL_HOST_USER # Desde donde se envian los mensajes
        recipient_list=[settings.EMAIL_HOST_RECIPIENT] #A donde llegan los mensajes enviados     

        formulario=ContactoForm(request.POST,auto_id='%s')

        if formulario.is_valid():
            
            info_formulario=formulario.cleaned_data

            subject=info_formulario['subject']
            email_client=info_formulario['email']
            name=info_formulario['name']
            message=info_formulario['message']
            
            contx={"name":name,"email_client":email_client,"subject":subject,"message":message,"email_from":email_from,"recipient_list":recipient_list}

            status_envio_email= envio_email(contx)






            #Limpia el formulario
            formulario=ContactoForm(auto_id='%s')
            
            #return HttpResponseRedirect('/contact')
            return render(request,'Contacto/contactForm.html',{"form":formulario,"envio":status_envio_email})

        # else:
            
        #     return render(request, 'Contacto/contactForm.html', context={'form': formulario})

            
    else:
        formulario=ContactoForm(auto_id='%s') # EL formulario Vacio
    return render(request,'Contacto/contactForm.html',{"form":formulario})


        
        
        

    

templates/AJ/LogIn.html
{% extends "AJ/base.html" %}

{% load static %}

{% block content1 %}


<h2>Esto esta en construccion y tiene que ser una App diferente</h2> 

{% endblock %}

templates/AJ/about.html
{% extends "AJ/base.html" %}

{% load static %}

{% block content %}


  <!-- ======= About Section ======= -->
  <section id="about" class="about">

    <!-- ======= About Me ======= -->
    <div class="about-me container">

      <div class="section-title">
        <h2>About</h2>
        <p>Learn more about me</p>
      </div>

      <div class="row">
        <div class="col-lg-4" data-aos="fade-right">
          <img src="{% static 'AJ/img/me.jpg' %}" class="img-fluid" alt="">
        </div>
        <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
          <h3>UI/UX &amp; Graphic Designer</h3>
          <p class="font-italic">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
            magna aliqua.
          </p>
          <div class="row">
            <div class="col-lg-6">
              <ul>
                <li><i class="icofont-rounded-right"></i> <strong>Birthday:</strong> 1 May 1995</li>
                <li><i class="icofont-rounded-right"></i> <strong>Website:</strong> www.example.com</li>
                <li><i class="icofont-rounded-right"></i> <strong>Phone:</strong> +123 456 7890</li>
                <li><i class="icofont-rounded-right"></i> <strong>City:</strong> City : New York, USA</li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul>
                <li><i class="icofont-rounded-right"></i> <strong>Age:</strong> 30</li>
                <li><i class="icofont-rounded-right"></i> <strong>Degree:</strong> Master</li>
                <li><i class="icofont-rounded-right"></i> <strong>PhEmailone:</strong> email@example.com</li>
                <li><i class="icofont-rounded-right"></i> <strong>Freelance:</strong> Available</li>
              </ul>
            </div>
          </div>
          <p>
            Officiis eligendi itaque labore et dolorum mollitia officiis optio vero. Quisquam sunt adipisci omnis et ut. Nulla accusantium dolor incidunt officia tempore. Et eius omnis.
            Cupiditate ut dicta maxime officiis quidem quia. Sed et consectetur qui quia repellendus itaque neque. Aliquid amet quidem ut quaerat cupiditate. Ab et eum qui repellendus omnis culpa magni laudantium dolores.
          </p>
        </div>
      </div>

    </div><!-- End About Me -->

    <!-- ======= Counts ======= -->
    <div class="counts container">

      <div class="row">

        <div class="col-lg-3 col-md-6">
          <div class="count-box">
            <i class="icofont-simple-smile"></i>
            <span data-toggle="counter-up">232</span>
            <p>Happy Clients</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-5 mt-md-0">
          <div class="count-box">
            <i class="icofont-document-folder"></i>
            <span data-toggle="counter-up">521</span>
            <p>Projects</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
          <div class="count-box">
            <i class="icofont-live-support"></i>
            <span data-toggle="counter-up">1,463</span>
            <p>Hours Of Support</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
          <div class="count-box">
            <i class="icofont-users-alt-5"></i>
            <span data-toggle="counter-up">15</span>
            <p>Hard Workers</p>
          </div>
        </div>

      </div>

    </div><!-- End Counts -->

    <!-- ======= Skills  ======= -->
    <div class="skills container">

      <div class="section-title">
        <h2>Skills</h2>
      </div>

      <div class="row skills-content">

        <div class="col-lg-6">

          <div class="progress">
            <span class="skill">HTML <i class="val">100%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">CSS <i class="val">90%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">JavaScript <i class="val">75%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

        </div>

        <div class="col-lg-6">

          <div class="progress">
            <span class="skill">PHP <i class="val">80%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">WordPress/CMS <i class="val">90%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">Photoshop <i class="val">55%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

        </div>

      </div>

    </div><!-- End Skills -->

    <!-- ======= Interests ======= -->
    <div class="interests container">

      <div class="section-title">
        <h2>Interests</h2>
      </div>

      <div class="row">
        <div class="col-lg-3 col-md-4">
          <div class="icon-box">
            <i class="ri-store-line" style="color: #ffbb2c;"></i>
            <h3>Lorem Ipsum</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4 mt-md-0">
          <div class="icon-box">
            <i class="ri-bar-chart-box-line" style="color: #5578ff;"></i>
            <h3>Dolor Sitema</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4 mt-md-0">
          <div class="icon-box">
            <i class="ri-calendar-todo-line" style="color: #e80368;"></i>
            <h3>Sed perspiciatis</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4 mt-lg-0">
          <div class="icon-box">
            <i class="ri-paint-brush-line" style="color: #e361ff;"></i>
            <h3>Magni Dolores</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4">
          <div class="icon-box">
            <i class="ri-database-2-line" style="color: #47aeff;"></i>
            <h3>Nemo Enim</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4">
          <div class="icon-box">
            <i class="ri-gradienter-line" style="color: #ffa76e;"></i>
            <h3>Eiusmod Tempor</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4">
          <div class="icon-box">
            <i class="ri-file-list-3-line" style="color: #11dbcf;"></i>
            <h3>Midela Teren</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4">
          <div class="icon-box">
            <i class="ri-price-tag-2-line" style="color: #4233ff;"></i>
            <h3>Pira Neve</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4">
          <div class="icon-box">
            <i class="ri-anchor-line" style="color: #b2904f;"></i>
            <h3>Dirada Pack</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4">
          <div class="icon-box">
            <i class="ri-disc-line" style="color: #b20969;"></i>
            <h3>Moton Ideal</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4">
          <div class="icon-box">
            <i class="ri-base-station-line" style="color: #ff5828;"></i>
            <h3>Verdo Park</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4">
          <div class="icon-box">
            <i class="ri-fingerprint-line" style="color: #29cc61;"></i>
            <h3>Flavor Nivelanda</h3>
          </div>
        </div>
      </div>

    </div><!-- End Interests -->

    <!-- ======= Testimonials ======= -->
    <div class="testimonials container">

      <div class="section-title">
        <h2>Testimonials</h2>
      </div>

      <div class="owl-carousel testimonials-carousel">

        <div class="testimonial-item">
          <p>
            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
            Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.
            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
          </p>
          <img src="{% static 'AJ/img/testimonials/testimonials-1.jpg' %}" class="testimonial-img" alt="">
          <h3>Saul Goodman</h3>
          <h4>Ceo &amp; Founder</h4>
        </div>

        <div class="testimonial-item">
          <p>
            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
            Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.
            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
          </p>
          <img src="{% static 'AJ/img/testimonials/testimonials-2.jpg' %}" class="testimonial-img" alt="">
          <h3>Sara Wilsson</h3>
          <h4>Designer</h4>
        </div>

        <div class="testimonial-item">
          <p>
            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
            Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.
            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
          </p>
          <img src="{% static 'AJ/img/testimonials/testimonials-3.jpg' %}" class="testimonial-img" alt="">
          <h3>Jena Karlis</h3>
          <h4>Store Owner</h4>
        </div>

        <div class="testimonial-item">
          <p>
            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
            Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
          </p>
          <img src="{% static 'AJ/img/testimonials/testimonials-4.jpg' %}" class="testimonial-img" alt="">
          <h3>Matt Brandon</h3>
          <h4>Freelancer</h4>
        </div>

        <div class="testimonial-item">
          <p>
            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
            Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi cillum quid.
            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
          </p>
          <img src="{% static 'AJ/img/testimonials/testimonials-5.jpg' %}" class="testimonial-img" alt="">
          <h3>John Larson</h3>
          <h4>Entrepreneur</h4>
        </div>

      </div>

    </div><!-- End Testimonials  -->

  </section><!-- End About Section -->


{% endblock %}

templates/AJ/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Personal AJ</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  {% load static %}

  <!-- Favicons -->
  <link href="{% static 'AJ/img/favicon.png' %}" rel="icon">
  <link href="{% static 'AJ/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'AJ/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'AJ/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'AJ/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'AJ/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'AJ/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'AJ/vendor/venobox/venobox.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'AJ/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Personal - v2.4.0
  * Template URL: https://bootstrapmade.com/personal-free-resume-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header-tops">
    <div class="container">

      <h1><a href="{% url 'AJ:homeAj' %}">Alejandro Rodriguez</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="mr-auto"><img src="{% static 'AJ/img/logo.png" alt="" class="img-fluid"></a> -->
      {% block content1 %}
        <!-- Aqui va el contenido de la pagina de "HOME"-->
      {% endblock %}

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="{% url 'AJ:homeAj' %}">Home</a></li>
          <li><a href="{% url 'AJ:about' %}#about">About</a></li>
          <li><a href="{% url 'AJ:resume' %}#resume">Resume</a></li>
          <li><a href="{% url 'AJ:services' %}#services">Services</a></li>
          <li><a href="{% url 'AJ:portfolio' %}#portfolio">Portfolio</a></li>
          <li><a href="{% url 'AJ:LogIn' %}">Log In</a></li>
          <li><a href="{% url 'Contacto:contact' %}#contact">Contact</a></li>
        </ul>
      </nav><!-- .nav-menu -->

      <div class="social-links">
        <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
        <a href="#" class="facebook"><i class="icofont-facebook"></i></a>
        <a href="#" class="instagram"><i class="icofont-instagram"></i></a>
        <a href="#" class="google-plus"><i class="icofont-skype"></i></a>
        <a href="#" class="linkedin"><i class="icofont-linkedin"></i></a>
      </div>

    </div>
  </header><!-- End Header -->

{% block content %}


{% endblock %}

  
  <div class="credits">
    <!-- All the links in the footer should remain intact. -->
    <!-- You can delete the links only if you purchased the pro version. -->
    <!-- Licensing information: https://bootstrapmade.com/license/ -->
    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/personal-free-resume-bootstrap-template/ -->
    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
  </div>

  <!-- Vendor JS Files -->
  <script src="{% static 'AJ/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'AJ/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'AJ/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'AJ/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'AJ/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'AJ/vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'AJ/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'AJ/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'AJ/vendor/venobox/venobox.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'AJ/js/main.js' %}"></script>

</body>

</html>

templates/AJ/home.html
{% extends "AJ/base.html" %}

{% load static %}

{% block content1 %}


<h2>I'm a passionate <span>trader</span> from anywhere</h2> 

{% endblock %}

templates/AJ/resume.html
{% extends "AJ/base.html" %}

{% load static %}

{% block content %}

<!-- ======= Resume Section ======= -->
<section id="resume" class="resume">
    <div class="container">

      <div class="section-title">
        <h2>Resume</h2>
        <p>Check My Resume</p>
      </div>

      <div class="row">
        <div class="col-lg-6">
          <h3 class="resume-title">Sumary</h3>
          <div class="resume-item pb-0">
            <h4>Alice Barkley</h4>
            <p><em>Innovative and deadline-driven Graphic Designer with 3+ years of experience designing and developing user-centered digital/print marketing material from initial concept to final, polished deliverable.</em></p>
            <p>
            <ul>
              <li>Portland par 127,Orlando, FL</li>
              <li>(123) 456-7891</li>
              <li>alice.barkley@example.com</li>
            </ul>
            </p>
          </div>

          <h3 class="resume-title">Education</h3>
          <div class="resume-item">
            <h4>Master of Fine Arts &amp; Graphic Design</h4>
            <h5>2015 - 2016</h5>
            <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
            <p>Qui deserunt veniam. Et sed aliquam labore tempore sed quisquam iusto autem sit. Ea vero voluptatum qui ut dignissimos deleniti nerada porti sand markend</p>
          </div>
          <div class="resume-item">
            <h4>Bachelor of Fine Arts &amp; Graphic Design</h4>
            <h5>2010 - 2014</h5>
            <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
            <p>Quia nobis sequi est occaecati aut. Repudiandae et iusto quae reiciendis et quis Eius vel ratione eius unde vitae rerum voluptates asperiores voluptatem Earum molestiae consequatur neque etlon sader mart dila</p>
          </div>
        </div>
        <div class="col-lg-6">
          <h3 class="resume-title">Professional Experience</h3>
          <div class="resume-item">
            <h4>Senior graphic design specialist</h4>
            <h5>2019 - Present</h5>
            <p><em>Experion, New York, NY </em></p>
            <p>
            <ul>
              <li>Lead in the design, development, and implementation of the graphic, layout, and production communication materials</li>
              <li>Delegate tasks to the 7 members of the design team and provide counsel on all aspects of the project. </li>
              <li>Supervise the assessment of all graphic materials in order to ensure quality and accuracy of the design</li>
              <li>Oversee the efficient use of production project budgets ranging from $2,000 - $25,000</li>
            </ul>
            </p>
          </div>
          <div class="resume-item">
            <h4>Graphic design specialist</h4>
            <h5>2017 - 2018</h5>
            <p><em>Stepping Stone Advertising, New York, NY</em></p>
            <p>
            <ul>
              <li>Developed numerous marketing programs (logos, brochures,infographics, presentations, and advertisements).</li>
              <li>Managed up to 5 projects or tasks at a given time while under pressure</li>
              <li>Recommended and consulted with clients on the most appropriate graphic design</li>
              <li>Created 4+ design presentations and proposals a month for clients and account managers</li>
            </ul>
            </p>
          </div>
        </div>
      </div>

    </div>
  </section><!-- End Resume Section -->
  
  {% endblock %}

templates/Contacto/email.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <h2>Name: {{name}}</h2>
    <h2>Email: {{email_client}}</h2>
    <h2></h2>Subject:{{subject}}</h2>


    <p>Message: {{message}}</p>


</body>
</html>